name: GitHub Pages

on:
  push:
    branches:
      - master # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest" # To use the latest version of Hugo.
          extended: true # To use a Hugo extended version.

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: yourgithubusername/yourreponame # Publish to another repository on GitHub
          publish_branch: master # default: gh-pages
          publish_dir: ./public # A source directory to deploy to GitHub Pages.
          enable_jekyll: false # If you want GitHub Pages to process your site with the static site generator Jekyll
          allow_empty_commit: true #  If you want to allow an empty commit
          force_orphan: true # This allows you to make your publish branch with only the latest commit.
